services:
  redis:
    image: redis:7.4-alpine
  cache-based:
    build:
      dockerfile: Dockerfile
      context: .
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - 8000-8001:8000
    working_dir: /app
    scale: 2
    depends_on:
      - redis
    environment:
      MAINTENANCE_DRIVER: cache
  file-based:
    build:
      dockerfile: Dockerfile
      context: .
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - 8002:8000
    working_dir: /app
    depends_on:
      - redis
    environment:
      MAINTENANCE_DRIVER: file
